[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"


[[redirects]]
  from = "/tts-models/*"
  to = "https://hf-mirror.com/api/resolve-cache/models/diffusionstudio/piper-voices/840e38a7e26d813bd6221b78cfbaefa3585b3f71/:splat"
  status = 200
  force = true
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), geolocation=(), microphone=()"

[[plugins]]
  package = "@netlify/plugin-nextjs"